---
abstract: 'Efficiently match IP addresses against IP ranges'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-IP-Match
provides:
  Net::IP::Match:
    file: lib/Net/IP/Match.pm
    version: 1.100860
requires:
  Benchmark: 0
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Filter::Simple: 0
  Net::Netmask: 0
  Scalar::Util: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Net-IP-Match
  homepage: http://search.cpan.org/dist/Net-IP-Match/
  repository: http://github.com/hanekomu/Net-IP-Match
version: 1.100860
